fail_fast: true
repos:
- repo: local
  hooks:
    - id: black
      name: black
      entry: poetry run black
      language: system
      types: [file, python]
    - id: isort
      name: isort
      entry: poetry run isort
      language: system
      types: [ file, python ]
    - id: pytest
      name: pytest
      entry: poetry run pytest
      language: system
      types: [ file, python ]
    - id: flake8
      name: flake8
      entry: poetry run flake8
      language: system
      types: [ file, python ]
      args: ['--max-line-length=88', '--extend-ignore=E203,E501,W503', '--exclude=.venv']
#-   repo: https://github.com/kynan/nbstripout
#    rev: '0.6.1'
#    hooks:
#    -   id: nbstripout
#-   repo: https://github.com/pycqa/pydocstyle
#    rev: '6.1.1'
#    hooks:
#    -   id: pydocstyle
#        args: ['--convention=google', '--add-ignore=D100,D101,D102,D103,D104,D105,D106,D107']
#-   repo: https://github.com/pre-commit/pre-commit-hooks
#    rev: 'v4.3.0'
#    hooks:
#    -   id: check-ast
#    -   id: end-of-file-fixer
#    -   id: trailing-whitespace
#-   repo: https://github.com/sqlfluff/sqlfluff
#    rev: '1.4.2'
#    hooks:
#    -   id: sqlfluff-fix
#    -   id: sqlfluff-lint